# -*- coding: utf-8 -*-
"""file.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ow-u5S5T3Zeo9NyDMIpBF7UJMGwCEy3f

# Great Expectations Task

## 1. Install Great Expectations Library
"""

!pip install great_expectations

"""##2. Import Necessary Libraries"""

import pandas as pd
import great_expectations as gx

"""##3. Load Labels.csv

Download and upload the [Labels.csv](https://github.com/zubxxr/SOFE3980U-Lab5/blob/main/Labels.csv) into this notebook, and then load the file.
"""

df = pd.read_csv("Labels.csv")

"""##4. Preview the Dataset"""

df.head()

"""##5. Set Up Great Expectations Context and Data Source"""

context = gx.get_context()

data_source = context.data_sources.add_pandas("pandas")

data_asset = data_source.add_dataframe_asset(name="labels_data")

"""##6. Define and Create a Data Batch"""

batch_definition = data_asset.add_batch_definition_whole_dataframe("batch_def")

batch = batch_definition.get_batch(
    batch_parameters={"dataframe": df}
)

"""##7. Define Three Expectations for Column Values

Using this [link](https://greatexpectations.io/expectations/), choose three expectation functions and apply them to the labels dataset in a relevant manner.

You should replace the 'ExpectColumnValuesToBeBetween' function with other functions you select from the link.

You can also check the format/parameters required of each function when you click "See more" on the function.
"""

## Original Function
expectation = gx.expectations.ExpectColumnValuesToBeBetween(
    column="column", min_value=0, max_value=20
)

## Example Function

## This function only requires a column parameter, and not a max or min value
expectation = gx.expectations.ExpectColumnValuesToBeUnique(
    column="column"
)

"""### Expectation 1"""

expectation1 = gx.expectations.ExpectColumnValuesToBeUnique(
    column="Timestamp"
)

"""### Validate Data Against Expectation 1"""

result1 = batch.validate(expectation1)
print(result1)

"""### Expectation 2"""

expectation2 = gx.expectations.ExpectColumnValuesToNotBeNull(
    column="Occluded_Image_view"
)

"""### Validate Data Against Expectation 2"""

result2 = batch.validate(expectation2)
print(result2)

"""### Expectation 3"""

expectation3 = gx.expectations.ExpectColumnPairValuesAToBeGreaterThanB(
    column_A="pedestrianLocationX_BottomRight",
    column_B="pedestrianLocationX_TopLeft"
)

"""### Validate Data Against Expectation 3"""

result3 = batch.validate(expectation3)
print(result3)